@ECHO OFF

SET CURRENT_DIR=%~dp0%

REM ### Variablen anpassen! #####################################
SET EB_GUIDE_INSTALL_PATH=C:/Elektrobit/"EB GUIDE 5.5.3"
SET EB_GUIDE_MODEL_NAME=eCARus_SS15
SET GENERATOR="Visual Studio 12"
REM SET GENERATOR="Visual Studio 9 2008"
REM #############################################################


SET SDK_PATH="%EB_GUIDE_INSTALL_PATH%/platform/win32"
REM SET APPLICATION_INSTALL_PATH=%EB_GUIDE_INSTALL_PATH%/projects/models/%EB_GUIDE_MODEL_NAME%/resources/target
SET APPLICATION_INSTALL_PATH=%CURRENT_DIR%/install

SET PARAMS=
SET PARAMS=%PARAMS% -DBUILD_STATIC_LINKED_APPLICATION:BOOL=OFF
SET PARAMS=%PARAMS% -DCLANG_ENABLE_ADDRESS_SANITIZER:BOOL=OFF
SET PARAMS=%PARAMS% -DCMAKE_INSTALL_PREFIX:PATH=%APPLICATION_INSTALL_PATH%
SET PARAMS=%PARAMS% -DGTF_GENERATE_ASSEMBLIES:BOOL=OFF
SET PARAMS=%PARAMS% -DGTF_TARGET_SDK_ROOT:PATH="%SDK_PATH%"
SET PARAMS=%PARAMS% -DGTF_TREAT_COMPILER_WARNINGS_AS_ERROR:BOOL=OFF


SET CMAKE_CMD="%CURRENT_DIR%CMake2.8.11\bin\cmake.exe"
SET CODE_DIR="%CURRENT_DIR%code"
SET WORKSPACE_DIR="%CURRENT_DIR%workspaces\win32"


rm -r %WORKSPACE_DIR%

mkdir %WORKSPACE_DIR%
cd %WORKSPACE_DIR%

%CMAKE_CMD% -G %GENERATOR% %PARAMS% %CODE_DIR% --trace 2> cmake_log.txt 

cd %CURRENT_DIR%
