@ECHO OFF

SET CURRENT_DIR=%~dp0%

REM ### Variablen anpassen! #####################################
SET EB_GUIDE_INSTALL_PATH=C:/Elektrobit/"EB GUIDE 5.5.3"
SET EB_GUIDE_MODEL_NAME=eCARus_SS15
SET ANDROID_TOOLCHAIN_DIR=%CURRENT_DIR%code/cmake/toolchain_android_test.cmake

SET ANDROID_NDK_ROOT=D:/Android/android-ndk-r10e
SET ANDROID_NDK_ANDROID_API=android-14
SET ANDROID_NDK_COMPILER_VER=4.8
REM #############################################################


SET SDK_PATH="%EB_GUIDE_INSTALL_PATH%/platform/android_9_armv7"
SET APPLICATION_INSTALL_PATH=%EB_GUIDE_INSTALL_PATH%/projects/models/%EB_GUIDE_MODEL_NAME%/resources/target

SET PARAMS=
SET PARAMS=%PARAMS% -DCMAKE_TOOLCHAIN_FILE:STRING=%ANDROID_TOOLCHAIN_DIR%
SET PARAMS=%PARAMS% -DANDROID_NDK_ROOT:STRING=%ANDROID_NDK_ROOT%
SET PARAMS=%PARAMS% -DANDROID_NDK_PREBUILT:STRING=windows-x86_64
SET PARAMS=%PARAMS% -DANDROID_NDK_ANDROID_API:STRING=%ANDROID_NDK_ANDROID_API%
SET PARAMS=%PARAMS% -DANDROID_NDK_COMPILER_VER:STRING=%ANDROID_NDK_COMPILER_VER%
SET PARAMS=%PARAMS% -DBUILD_STATIC_LINKED_APPLICATION:BOOL=OFF
SET PARAMS=%PARAMS% -DCLANG_ENABLE_ADDRESS_SANITIZER:BOOL=OFF
SET PARAMS=%PARAMS% -DCMAKE_INSTALL_PREFIX:PATH=%APPLICATION_INSTALL_PATH%
SET PARAMS=%PARAMS% -DGTF_GENERATE_ASSEMBLIES:BOOL=OFF
SET PARAMS=%PARAMS% -DGTF_TARGET_SDK_ROOT:PATH="%SDK_PATH%"
SET PARAMS=%PARAMS% -DGTF_TREAT_COMPILER_WARNINGS_AS_ERROR:BOOL=OFF


SET CODE_DIR="%CURRENT_DIR%code"
SET CMAKE_CMD="%CURRENT_DIR%CMake2.8.11\bin\cmake.exe"
SET WORKSPACE_DIR="%CURRENT_DIR%workspaces\android"
SET GENERATOR="Unix Makefiles"


rm -r %WORKSPACE_DIR%

mkdir %WORKSPACE_DIR%
cd %WORKSPACE_DIR%

%CMAKE_CMD% -G %GENERATOR% %PARAMS% %CODE_DIR% --trace 2> cmake_log.txt 

cd %CURRENT_DIR%
