/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gtflauncher_music_MusicJNIAccess */

#ifndef _Included_com_example_gtflauncher_music_MusicJNIAccess
#define _Included_com_example_gtflauncher_music_MusicJNIAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gtflauncher_music_MusicJNIAccess
 * Method:    updateTrackList
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_gtflauncher_music_MusicJNIAccess_updateTrackList
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
