/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gtflauncher_music_MusicJNIAccess */

#ifndef _Included_com_example_gtflauncher_music_MusicJNIAccess
#define _Included_com_example_gtflauncher_music_MusicJNIAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gtflauncher_music_MusicJNIAccess
 * Method:    addTitle
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_gtflauncher_music_MusicJNIAccess_addTitle
  (JNIEnv *, jclass, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
