/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gtflauncher_tower_TowerJNIAccess */

#ifndef _Included_com_example_gtflauncher_tower_TowerJNIAccess
#define _Included_com_example_gtflauncher_tower_TowerJNIAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gtflauncher_tower_TowerJNIAccess
 * Method:    onLightStateUpdated
 * Signature: (ZZZZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_gtflauncher_tower_TowerJNIAccess_onLightStateUpdated
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_example_gtflauncher_tower_TowerJNIAccess
 * Method:    onGestureDetected
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_gtflauncher_tower_TowerJNIAccess_onGestureDetected
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
